services:
    volleyball.controller.report:
        class: Volleyball\Bundle\ReportBundle\Controller\ReportController
        factory_service: sylius.controller.configuration_factory
        factory_method: createConfiguration
        arguments: ["sylius", "report", "VolleyballReportBundle:Report"]